# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage: Build
  jobs:
  - job: BuildJob
    steps: 
    - bash: echo "Build the job"
- stage: DevDeploy
  jobs:
  - job: BuildJob
    steps: 
    - bash: echo "Do the the Dev build"
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps: 
          - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  - job: BuildJob
    steps: 
    - bash: echo "Do the the Dev build"
  - deployment: QADeploy Job
    environment: QADeploy
    strategy:
      runOnce:
       deploy:
        steps: 
        - script: echo QADeploy to QA
   